### ISSUE TITLE
Recognize meta properties in DTBook

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#6]
A few meta elements that can probably be mapped to system settings or CSS:
- [x] prod:docType (string, "ro" or "sv") to determine title page, re #16
- [x] prod:docType (string, "ro" or "sv") to determine colophon, re #22
- [x] prod:docType (string, "ro" or "sv") to determine the value for show-print-page-numbers
- [x] prod:docHyphenate (boolean, 'Y'/'N')
- [x] prod:colophon (number, 1-3), re #22

**Comment by bertfrees** [comment]
If you think that is the expected behavior, OK. You should however think about what should happen if both are specified, and document that.
